This notebook will be used for capstone project for Applied Data Science Capstone course.

In [1]:
import pandas as pd
import numpy as np
print('Hello Capstone Project Course!')
print('github try')
print('second github try')

Hello Capstone Project Course!
github try
second github try

In [139]:
df = pd.read_csv('./Downloads/199387_1319582_compressed_US_Accidents_June20.csv/US_Accidents_June20.csv')
df.head()

,ID,Source,TMC,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,End_Lat,End_Lng,...,Roundabout,Station,Stop,Traffic_Calming,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Civil_Twilight,Nautical_Twilight,Astronomical_Twilight
0,A-1,MapQuest,201.0,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Night
1,A-2,MapQuest,201.0,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,NaN,NaN,...,False,False,False,False,False,False,Night,Night,Night,Day
2,A-3,MapQuest,201.0,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,NaN,NaN,...,False,False,False,False,True,False,Night,Night,Day,Day
3,A-4,MapQuest,201.0,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,NaN,NaN,...,False,False,False,False,False,False,Night,Day,Day,Day
4,A-5,MapQuest,201.0,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,NaN,NaN,...,False,False,False,False,True,False,Day,Day,Day,Day

In [51]:
df.columns

Index(['ID', 'Source', 'TMC', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'End_Lat', 'End_Lng', 'Distance(mi)',
       'Description', 'Number', 'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone', 'Airport_Code', 'Weather_Timestamp',
       'Temperature(F)', 'Wind_Chill(F)', 'Humidity(%)', 'Pressure(in)',
       'Visibility(mi)', 'Wind_Direction', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight'],
      dtype='object')

In [52]:
df.shape

(3513617, 49)

#### Data Cleaning

Let's only keep the columns that we are intersted.

In [166]:
columns_to_keep = ['ID', 'Severity', 'Start_Time', 'End_Time',
       'Start_Lat', 'Start_Lng', 'Distance(mi)',
       'Street', 'Side', 'City', 'County', 'State',
       'Zipcode', 'Country', 'Timezone',
       'Temperature(F)',
       'Visibility(mi)', 'Wind_Speed(mph)',
       'Precipitation(in)', 'Weather_Condition','Crossing',
       'Junction', 'Roundabout',
       'Traffic_Signal', 'Turning_Loop',
       'Sunrise_Sunset']

df1 = df[columns_to_keep]
df1.shape

(3513617, 26)

In [167]:
# to find the actual delay in terms of hours
df1['Start_Time'] = pd.to_datetime(df1['Start_Time'], format = "%Y/%m/%d %H:%M:%S")
df1['End_Time'] = pd.to_datetime(df1['End_Time'], format = "%Y/%m/%d %H:%M:%S")
df1['Time_Delay (Hrs)'] = (df1['End_Time'] - df1['Start_Time'])/np.timedelta64(1, 'h')
df1.head(10)

C:\Users\shambhu\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\shambhu\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\shambhu\anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,Side,City,...,Wind_Speed(mph),Precipitation(in),Weather_Condition,Crossing,Junction,Roundabout,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Time_Delay (Hrs)
0,A-1,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.01,I-70 E,R,Dayton,...,NaN,0.02,Light Rain,False,False,False,False,False,Night,5.233333
1,A-2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.01,Brice Rd,L,Reynoldsburg,...,NaN,0.00,Light Rain,False,False,False,False,False,Night,0.500000
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.01,State Route 32,R,Williamsburg,...,3.5,NaN,Overcast,False,False,False,True,False,Night,0.500000
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.01,I-75 S,R,Dayton,...,4.6,NaN,Mostly Cloudy,False,False,False,False,False,Night,0.500000
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.01,Miamisburg Centerville Rd,R,Dayton,...,3.5,NaN,Mostly Cloudy,False,False,False,True,False,Day,0.500000
5,A-6,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.01,Westerville Rd,R,Westerville,...,3.5,0.03,Light Rain,False,False,False,False,False,Day,0.500000
6,A-7,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.00,N Woodward Ave,R,Dayton,...,3.5,NaN,Overcast,False,False,False,False,False,Day,0.500000
7,A-8,3,2016-02-08 07:59:58,2016-02-08 08:29:58,39.770382,-84.194901,0.01,N Main St,R,Dayton,...,3.5,NaN,Overcast,False,False,False,False,False,Day,0.500000
8,A-9,2,2016-02-08 08:00:40,2016-02-08 08:30:40,39.778061,-84.172005,0.00,Notre Dame Ave,L,Dayton,...,1.2,NaN,Mostly Cloudy,False,False,False,False,False,Day,0.500000
9,A-10,3,2016-02-08 08:10:04,2016-02-08 08:40:04,40.100590,-82.925194,0.01,Westerville Rd,R,Westerville,...,4.6,0.02,Light Rain,False,False,False,False,False,Day,0.500000

In [168]:
# Let's get day of week
df1['Day_Of_Week'] = df1['Start_Time'].dt.weekday
#df1['Name_Of_Day'] = df1['Start_Time'].dt.weekday_name
df1['Day_Of_Week'].value_counts()

C:\Users\shambhu\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

4    639706
1    631136
2    624429
3    621677
0    592871
5    214483
6    189315
Name: Day_Of_Week, dtype: int64

In [170]:
df1[['Severity', 'Day_Of_Week']].corr()

             Severity  Day_Of_Week
Severity      1.00000      0.07443
Day_Of_Week   0.07443      1.00000

In [89]:
df['Time_Delay (Hrs)'].describe()

count    3.513617e+06
mean     1.921973e+00
std      5.633991e+01
min     -5.680556e-01
25%      4.955556e-01
50%      7.444444e-01
75%      1.249444e+00
max      2.369926e+04
Name: Time_Delay (Hrs), dtype: float64

In [105]:
df['Weather_Condition'].value_counts()

Clear                           808202
Fair                            547721
Mostly Cloudy                   488094
Overcast                        382485
Partly Cloudy                   344815
                                 ...
Thunder and Hail                     1
Freezing Rain / Windy                1
Thunder / Wintry Mix / Windy         1
Snow and Thunder                     1
Partial Fog / Windy                  1
Name: Weather_Condition, Length: 127, dtype: int64

##### Dealing with missing values

In [142]:
# Let's count the number of missing values in each columns
missing_data = df1.isnull()
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

ID
False    3513617
Name: ID, dtype: int64

Severity
False    3513617
Name: Severity, dtype: int64

Start_Time
False    3513617
Name: Start_Time, dtype: int64

End_Time
False    3513617
Name: End_Time, dtype: int64

Start_Lat
False    3513617
Name: Start_Lat, dtype: int64

Start_Lng
False    3513617
Name: Start_Lng, dtype: int64

Distance(mi)
False    3513617
Name: Distance(mi), dtype: int64

Street
False    3513617
Name: Street, dtype: int64

Side
False    3513617
Name: Side, dtype: int64

City
False    3513505
True         112
Name: City, dtype: int64

County
False    3513617
Name: County, dtype: int64

State
False    3513617
Name: State, dtype: int64

Zipcode
False    3512548
True        1069
Name: Zipcode, dtype: int64

Country
False    3513617
Name: Country, dtype: int64

Timezone
False    3509737
True        3880
Name: Timezone, dtype: int64

Temperature(F)
False    3447885
True       65732
Name: Temperature(F), dtype: int64

Visibility(mi)
False    3437761
True       75856
Name: Visibility(mi), dtype: int64

Wind_Speed(mph)
False    3059008
True      454609
Name: Wind_Speed(mph), dtype: int64

Precipitation(in)
True     2025874
False    1487743
Name: Precipitation(in), dtype: int64

Weather_Condition
False    3437479
True       76138
Name: Weather_Condition, dtype: int64

Crossing
False    3513617
Name: Crossing, dtype: int64

Junction
False    3513617
Name: Junction, dtype: int64

Roundabout
False    3513617
Name: Roundabout, dtype: int64

Traffic_Signal
False    3513617
Name: Traffic_Signal, dtype: int64

Turning_Loop
False    3513617
Name: Turning_Loop, dtype: int64

Sunrise_Sunset
False    3513502
True         115
Name: Sunrise_Sunset, dtype: int64

Time_Delay (Hrs)
False    3513617
Name: Time_Delay (Hrs), dtype: int64

Since the __Precipitation__ column is missing 2,025,874 values, hence instead drop all rows we want to replace the missing values with mean.

In [143]:
average = df1['Precipitation(in)'].astype('float').mean()
df1['Precipitation(in)'].replace(np.nan, average, inplace=True)

C:\Users\shambhu\anaconda3\lib\site-packages\pandas\core\generic.py:6746: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

For missing values among other columns, we simply drop the rows containing the missing values.

In [144]:
df1.dropna(subset = ['City', 'Temperature(F)', 'Visibility(mi)', 'Wind_Speed(mph)','Weather_Condition', 'Sunrise_Sunset'], axis = 0)

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,Side,City,...,Wind_Speed(mph),Precipitation(in),Weather_Condition,Crossing,Junction,Roundabout,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Time_Delay (Hrs)
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,State Route 32,R,Williamsburg,...,3.5,0.015983,Overcast,False,False,False,True,False,Night,0.500000
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,I-75 S,R,Dayton,...,4.6,0.015983,Mostly Cloudy,False,False,False,False,False,Night,0.500000
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Miamisburg Centerville Rd,R,Dayton,...,3.5,0.015983,Mostly Cloudy,False,False,False,True,False,Day,0.500000
5,A-6,3,2016-02-08 07:44:26,2016-02-08 08:14:26,40.100590,-82.925194,0.010,Westerville Rd,R,Westerville,...,3.5,0.030000,Light Rain,False,False,False,False,False,Day,0.500000
6,A-7,2,2016-02-08 07:59:35,2016-02-08 08:29:35,39.758274,-84.230507,0.000,N Woodward Ave,R,Dayton,...,3.5,0.015983,Overcast,False,False,False,False,False,Day,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513612,A-3513776,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,Pomona Fwy E,R,Riverside,...,13.0,0.000000,Fair,False,False,False,False,False,Day,0.476667
3513613,A-3513777,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,I-8 W,R,San Diego,...,6.0,0.000000,Fair,False,False,False,False,False,Day,0.448056
3513614,A-3513778,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,Garden Grove Fwy,R,Orange,...,10.0,0.000000,Partly Cloudy,False,True,False,False,False,Day,0.474444
3513615,A-3513779,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,San Diego Fwy S,R,Culver City,...,8.0,0.000000,Fair,False,False,False,False,False,Day,0.489167
3513616,A-3513780,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,CA-210 W,R,Highland,...,7.0,0.000000,Fair,False,False,False,False,False,Day,0.490278

##### Formatting the data

In [145]:
# Let's check the datatypes
df1.dtypes

ID                           object
Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
Start_Lat                   float64
Start_Lng                   float64
Distance(mi)                float64
Street                       object
Side                         object
City                         object
County                       object
State                        object
Zipcode                      object
Country                      object
Timezone                     object
Temperature(F)              float64
Visibility(mi)              float64
Wind_Speed(mph)             float64
Precipitation(in)           float64
Weather_Condition            object
Crossing                       bool
Junction                       bool
Roundabout                     bool
Traffic_Signal                 bool
Turning_Loop                   bool
Sunrise_Sunset               object
Time_Delay (Hrs)            float64
dtype: object

We want to convert the boolean data into numerical values as; 1 for True and 0 for false

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,Side,City,...,Wind_Speed(mph),Precipitation(in),Weather_Condition,Crossing,Junction,Roundabout,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Time_Delay (Hrs)
0,A-1,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.010,I-70 E,R,Dayton,...,NaN,0.020000,Light Rain,False,False,False,0,False,Night,5.233333
1,A-2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.010,Brice Rd,L,Reynoldsburg,...,NaN,0.000000,Light Rain,False,False,False,0,False,Night,0.500000
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,State Route 32,R,Williamsburg,...,3.5,0.015983,Overcast,False,False,False,1,False,Night,0.500000
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,I-75 S,R,Dayton,...,4.6,0.015983,Mostly Cloudy,False,False,False,0,False,Night,0.500000
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Miamisburg Centerville Rd,R,Dayton,...,3.5,0.015983,Mostly Cloudy,False,False,False,1,False,Day,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513612,A-3513776,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,Pomona Fwy E,R,Riverside,...,13.0,0.000000,Fair,False,False,False,0,False,Day,0.476667
3513613,A-3513777,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,I-8 W,R,San Diego,...,6.0,0.000000,Fair,False,False,False,0,False,Day,0.448056
3513614,A-3513778,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,Garden Grove Fwy,R,Orange,...,10.0,0.000000,Partly Cloudy,False,True,False,0,False,Day,0.474444
3513615,A-3513779,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,San Diego Fwy S,R,Culver City,...,8.0,0.000000,Fair,False,False,False,0,False,Day,0.489167
3513616,A-3513780,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,CA-210 W,R,Highland,...,7.0,0.000000,Fair,False,False,False,0,False,Day,0.490278

In [152]:
# Similarly let's assing 1 and 0 for other columns containing boolean data
df1.replace([True, False], [1, 0])

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Distance(mi),Street,Side,City,...,Wind_Speed(mph),Precipitation(in),Weather_Condition,Crossing,Junction,Roundabout,Traffic_Signal,Turning_Loop,Sunrise_Sunset,Time_Delay (Hrs)
0,A-1,3,2016-02-08 05:46:00,2016-02-08 11:00:00,39.865147,-84.058723,0.010,I-70 E,R,Dayton,...,NaN,0.020000,Light Rain,0,0,0,0,0,Night,5.233333
1,A-2,2,2016-02-08 06:07:59,2016-02-08 06:37:59,39.928059,-82.831184,0.010,Brice Rd,L,Reynoldsburg,...,NaN,0.000000,Light Rain,0,0,0,0,0,Night,0.500000
2,A-3,2,2016-02-08 06:49:27,2016-02-08 07:19:27,39.063148,-84.032608,0.010,State Route 32,R,Williamsburg,...,3.5,0.015983,Overcast,0,0,0,1,0,Night,0.500000
3,A-4,3,2016-02-08 07:23:34,2016-02-08 07:53:34,39.747753,-84.205582,0.010,I-75 S,R,Dayton,...,4.6,0.015983,Mostly Cloudy,0,0,0,0,0,Night,0.500000
4,A-5,2,2016-02-08 07:39:07,2016-02-08 08:09:07,39.627781,-84.188354,0.010,Miamisburg Centerville Rd,R,Dayton,...,3.5,0.015983,Mostly Cloudy,0,0,0,1,0,Day,0.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3513612,A-3513776,2,2019-08-23 18:03:25,2019-08-23 18:32:01,34.002480,-117.379360,0.543,Pomona Fwy E,R,Riverside,...,13.0,0.000000,Fair,0,0,0,0,0,Day,0.476667
3513613,A-3513777,2,2019-08-23 19:11:30,2019-08-23 19:38:23,32.766960,-117.148060,0.338,I-8 W,R,San Diego,...,6.0,0.000000,Fair,0,0,0,0,0,Day,0.448056
3513614,A-3513778,2,2019-08-23 19:00:21,2019-08-23 19:28:49,33.775450,-117.847790,0.561,Garden Grove Fwy,R,Orange,...,10.0,0.000000,Partly Cloudy,0,1,0,0,0,Day,0.474444
3513615,A-3513779,2,2019-08-23 19:00:21,2019-08-23 19:29:42,33.992460,-118.403020,0.772,San Diego Fwy S,R,Culver City,...,8.0,0.000000,Fair,0,0,0,0,0,Day,0.489167
3513616,A-3513780,2,2019-08-23 18:52:06,2019-08-23 19:21:31,34.133930,-117.230920,0.537,CA-210 W,R,Highland,...,7.0,0.000000,Fair,0,0,0,0,0,Day,0.490278

In [153]:
df1.dtypes

ID                           object
Severity                      int64
Start_Time           datetime64[ns]
End_Time             datetime64[ns]
Start_Lat                   float64
Start_Lng                   float64
Distance(mi)                float64
Street                       object
Side                         object
City                         object
County                       object
State                        object
Zipcode                      object
Country                      object
Timezone                     object
Temperature(F)              float64
Visibility(mi)              float64
Wind_Speed(mph)             float64
Precipitation(in)           float64
Weather_Condition            object
Crossing                       bool
Junction                       bool
Roundabout                     bool
Traffic_Signal                 bool
Turning_Loop                   bool
Sunrise_Sunset               object
Time_Delay (Hrs)            float64
dtype: object

In [ ]:
df1_Sev = df1[['Severity', 'Time_Delay (Hrs)']]
df1_Sev = df1_Sev.set_index('Severity')
df1_Sev[1] = df1_Sev.loc[1, 'Time_Delay (Hrs)']
df1.Sev.head()